// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayAchievement
{
        public const string achievement_im_one_of_two_hundred = "CgkImfmT7tgGEAIQBQ"; // <GPGSID>
        public const string achievement_plus_ultra = "CgkImfmT7tgGEAIQCQ"; // <GPGSID>
        public const string achievement_my_first_100_points = "CgkImfmT7tgGEAIQAQ"; // <GPGSID>
        public const string achievement_im_just_trying_to_survive_as_a_millenial = "CgkImfmT7tgGEAIQBw"; // <GPGSID>
        public const string achievement_geezus_i_think_i_stop_giving_you_more_rewards_wait_until_next_patch = "CgkImfmT7tgGEAIQCA"; // <GPGSID>
        public const string leaderboard_highscore = "CgkImfmT7tgGEAIQAw"; // <GPGSID>
        public const string achievement_this_is_my_first_time_she_said = "CgkImfmT7tgGEAIQBg"; // <GPGSID>
        public const string achievement_collect_em_all = "CgkImfmT7tgGEAIQBA"; // <GPGSID>

}

